name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Deno environment
      uses: denolib/setup-deno@v1.3.0
      # with:
        # Version range or exact version of a Deno version to use.
        # deno-version: # optional, default is v0.x

    - name: Run tests
      run: |
          deno test
          deno run examples/simple.ts
          deno run examples/async.ts
          deno run examples/callbacks.ts
#          deno fmt **/*.ts --check
